### PR TITLE
Flowered Water Lily Generation

### PR DESCRIPTION
**Pull request by Albertsmods**
I also removed sodium and iris from the copper horns sound folder

### CODE REVIEW

**Comment by MerpisMe** [comment]
we're planning on making flowered lilypads part of the base lilypad block, so we may have to decline this pr

**Comment by Albertsmods** [comment]
ok

**Comment by Soro335** [comment]
> I also removed sodium and iris from the copper horns sound folder

Thank u, but flowered water lily is not finished yet. Do you know how to remove vanila features from vanila biomes?

**Comment by Albertsmods** [comment]
> Do you know how to remove vanila features from vanila biomes?
Sadly not

**Comment by BluePhoenixLOL** [comment]
> I also removed sodium and iris from the copper horns sound folder

how did that get there whoops

**Comment by BluePhoenixLOL** [comment]
so

**Pull request closed without merging**
